#
# Copyright (C) 2020 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD_VENDOR := samsung
DEVICE_PATH := device/samsung/m11q
ALLOW_MISSING_DEPENDENCIES=true
BUILD_BROKEN_DUP_RULES := true

# Platform
BOARD_VENDOR := samsung
TARGET_BOARD_PLATFORM := sdm450
TARGET_BOARD_PLATFORM_GPU := qcom-adreno506

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_PATH)/bluetooth
BOARD_HAVE_BLUETOOTH_QCOM := true
BLUETOOTH_HCI_USE_MCT := true
TARGET_USE_QTI_BT_STACK := true